services:
  - type: web
    name: catalogo-peliculas-api
    plan: free
    region: oregon
    root: backend
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
    startCommand: |
      php artisan migrate --force
      php -S 0.0.0.0:$PORT public/index.php
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false

  - type: static
    name: catalogo-peliculas-web
    plan: free
    region: oregon
    root: frontend
    buildCommand: |
      npm install
      npm run build
    publishPath: dist/frontend