services:
  - type: web
    name: catalogo-peliculas-app
    plan: free
    region: oregon
    docker:
      dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
      - fromDatabase:
          name: catalogo-peliculas-db
          property: connectionString

databases:
  - name: catalogo-peliculas-db
    plan: free
    region: oregon
    databaseName: catalogo_peliculas
    user: catalogo_user
