services:
  - type: web
    name: catalogo-peliculas-completo
    env: docker
    plan: free
    docker:
      dockerfile: Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://catalogo-peliculas-udgvitual.onrender.com
      - key: LOG_CHANNEL
        value: stderr
    numInstances: 1
